### ISSUE TITLE
\cvsubitem{} does not appear to work

### ISSUE THREAD

**Issue by aroline-c** [hnqiu/simplecv#1]
Just thought of bringing this to your attention. I copied and pasted your cv.tex onto my Overleaf to verify if it wasn't an error on my end. I am seeing that lines 35 and 36 of your cv.tex are prompted with 'undefined control sequence'.

**Comment by aroline-c** [comment]
I was just being ignorant. I realize I copied the .cls file from a friend who deleted \cvsubitem{} from there. I apologize.

**Comment by hnqiu** [comment]
No worries
